import type { ImageRequireSource } from 'react-native';

export const CONCENTRATE_IMAGES: Record<string, ImageRequireSource> = {
  'live-rosin':       require('../../assets/concentrates/live-rosin.png'),
  'cold-cure':        require('../../assets/concentrates/cold-cure.png'),
  'fresh-press':      require('../../assets/concentrates/fresh-press.png'),
  'rosin-jam':        require('../../assets/concentrates/rosin-jam.png'),
  'rosin-badder':     require('../../assets/concentrates/rosin-badder.png'),
  'hot-cure':         require('../../assets/concentrates/hot-cure.png'),
  'hash-rosin-coin':  require('../../assets/concentrates/hash-rosin-coin.png'),
  'persy-rosin':      require('../../assets/concentrates/persy-rosin.png'),
  'high-melt-rosin':  require('../../assets/concentrates/high-melt-rosin.png'),
  'bubble-6star':     require('../../assets/concentrates/bubble-6star.png'),
  'bubble-half-melt': require('../../assets/concentrates/bubble-half-melt.png'),
  'dry-sift':         require('../../assets/concentrates/dry-sift.png'),
  'temple-ball':      require('../../assets/concentrates/temple-ball.png'),
  'pressed-hash':     require('../../assets/concentrates/pressed-hash.png'),
  'live-resin':       require('../../assets/concentrates/live-resin.png'),
  'cured-resin':      require('../../assets/concentrates/cured-resin.png'),
  'shatter':          require('../../assets/concentrates/shatter.png'),
  'wax-budder':       require('../../assets/concentrates/wax-budder.png'),
  'crumble':          require('../../assets/concentrates/crumble.png'),
  'sugar':            require('../../assets/concentrates/sugar.png'),
  'sauce-htfse':      require('../../assets/concentrates/sauce-htfse.png'),
  'thca-diamonds':    require('../../assets/concentrates/thca-diamonds.png'),
  'diamonds-sauce':   require('../../assets/concentrates/diamonds-sauce.png'),
  'crystalline':      require('../../assets/concentrates/crystalline.png'),
  'liquid-diamonds':  require('../../assets/concentrates/liquid-diamonds.png'),
  'co2-oil':          require('../../assets/concentrates/co2-oil.png'),
  'thc-distillate':   require('../../assets/concentrates/thc-distillate.png'),
  'cbn-distillate':   require('../../assets/concentrates/cbn-distillate.png'),
  'cbg-distillate':   require('../../assets/concentrates/cbg-distillate.png'),
  'thcv-distillate':  require('../../assets/concentrates/thcv-distillate.png'),
  'infused-diamonds': require('../../assets/concentrates/infused-diamonds.png'),
  'thcp':             require('../../assets/concentrates/thcp.png'),
  'hash-holes':       require('../../assets/concentrates/hash-holes.png'),
  'kief':             require('../../assets/concentrates/kief.png'),
  'rso':              require('../../assets/concentrates/rso.png'),
  'bubble-1-2':       require('../../assets/concentrates/bubble-1-2.png'),
};
