import type { ImageRequireSource } from 'react-native';

export const CONCENTRATE_IMAGES: Record<string, ImageRequireSource> = {
  'live-rosin':       require('../../assets/cocnentrates/live-rosin.png'),
  'cold-cure':        require('../../assets/cocnentrates/cold-cure.png'),
  'fresh-press':      require('../../assets/cocnentrates/fresh-press.png'),
  'rosin-jam':        require('../../assets/cocnentrates/rosin-jam.png'),
  'rosin-badder':     require('../../assets/cocnentrates/rosin-badder.png'),
  'hot-cure':         require('../../assets/cocnentrates/hot-cure.png'),
  'hash-rosin-coin':  require('../../assets/cocnentrates/hash-rosin-coin.png'),
  'persy-rosin':      require('../../assets/cocnentrates/persy-rosin.png'),
  'high-melt-rosin':  require('../../assets/cocnentrates/high-melt-rosin.png'),
  'bubble-6star':     require('../../assets/cocnentrates/bubble-6star.png'),
  'bubble-half-melt': require('../../assets/cocnentrates/bubble-half-melt.png'),
  'dry-sift':         require('../../assets/cocnentrates/dry-sift.png'),
  'temple-ball':      require('../../assets/cocnentrates/temple-ball.png'),
  'pressed-hash':     require('../../assets/cocnentrates/pressed-hash.png'),
  'live-resin':       require('../../assets/cocnentrates/live-resin.png'),
  'cured-resin':      require('../../assets/cocnentrates/cured-resin.png'),
  'shatter':          require('../../assets/cocnentrates/shatter.png'),
  'wax-budder':       require('../../assets/cocnentrates/wax-budder.png'),
  'crumble':          require('../../assets/cocnentrates/crumble.png'),
  'sugar':            require('../../assets/cocnentrates/sugar.png'),
  'sauce-htfse':      require('../../assets/cocnentrates/sauce-htfse.png'),
  'thca-diamonds':    require('../../assets/cocnentrates/thca-diamonds.png'),
  'diamonds-sauce':   require('../../assets/cocnentrates/diamonds-sauce.png'),
  'crystalline':      require('../../assets/cocnentrates/crystalline.png'),
  'liquid-diamonds':  require('../../assets/cocnentrates/liquid-diamonds.png'),
  'co2-oil':          require('../../assets/cocnentrates/co2-oil.png'),
  'thc-distillate':   require('../../assets/cocnentrates/thc-distillate.png'),
  'cbn-distillate':   require('../../assets/cocnentrates/cbn-distillate.png'),
  'cbg-distillate':   require('../../assets/cocnentrates/cbg-distillate.png'),
  'thcv-distillate':  require('../../assets/cocnentrates/thcv-distillate.png'),
  'infused-diamonds': require('../../assets/cocnentrates/infused-diamonds.png'),
  'thcp':             require('../../assets/cocnentrates/thcp.png'),
  'hash-holes':       require('../../assets/cocnentrates/hash-holes.png'),
  'kief':             require('../../assets/cocnentrates/kief.png'),
  'rso':              require('../../assets/cocnentrates/rso.png'),
  'bubble-1-2':       require('../../assets/cocnentrates/bubble-1-2.png'),
};
