name: EAS Update

on:
  push:
    branches: ['**']

jobs:
  update:
    uses: joshuapointer/eas-workflows/.github/workflows/update.yml@main
    with:
      platform: all
      npm_flags: --legacy-peer-deps
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
